model:
  pretrained: false
  arch: hg2
  activation: relu
  norm: batch
  weight_std:  True

  num_stacks: 2
  num_blocks: 1
  num_classes: 16

  compress_ratio: 2

optimizer:
  optimizer: adamw
  lr: !!float 1e-3
  epochs: 30
  betas: [0.9, 0.999]
  eps: !!float 1e-8
  weight_decay: !!float 0

scheduler:
  T_max: 30000
  eta_min: !!float 1e-6
