model:
  pretrained: false
  arch: lpn
  resnet_spec: 152
  use_gcb: true
  activation: relu
  norm: batch
  weight_std: False

  num_stacks: 2
  num_blocks: 1
  num_classes: 16

optimizer:
  optimizer: adamw
  lr: !!float 1e-3
  epochs: 30
  betas: [0.9, 0.999]
  eps: !!float 1e-8
  weight_decay: !!float 0

scheduler:
  T_max: 30000
  eta_min: !!float 1e-6